sudo: false

language: node_js

node_js:
  - "0.10"
  - "4"
  - "6"

before_script:
  - mkdir -p gnatsd
  - wget https://github.com/nats-io/gnatsd/releases/download/v0.9.6/gnatsd-v0.9.6-linux-amd64.zip -qO - | tar -zxv --strip-components=1 -C gnatsd/
  - ./gnatsd/gnatsd &

after_success:
  - npm run test:coveralls